/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LabRouteImport } from './routes/lab'
import { Route as MatchupRouteImport } from './routes/matchup'
import { Route as DexIndexRouteImport } from './routes/dex/index'
import { Route as DexIdRouteImport } from './routes/dex/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupRoute = MatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => rootRouteImport,
} as any)
const DexIndexRoute = DexIndexRouteImport.update({
  id: '/dex/',
  path: '/dex/',
  getParentRoute: () => rootRouteImport,
} as any)
const DexIdRoute = DexIdRouteImport.update({
  id: '/dex/$id',
  path: '/dex/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/lab': typeof LabRoute
  '/matchup': typeof MatchupRoute
  '/dex/$id': typeof DexIdRoute
  '/dex/': typeof DexIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/lab': typeof LabRoute
  '/matchup': typeof MatchupRoute
  '/dex/$id': typeof DexIdRoute
  '/dex': typeof DexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/lab': typeof LabRoute
  '/matchup': typeof MatchupRoute
  '/dex/$id': typeof DexIdRoute
  '/dex/': typeof DexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guide' | '/lab' | '/matchup' | '/dex/$id' | '/dex/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guide' | '/lab' | '/matchup' | '/dex/$id' | '/dex'
  id: '__root__' | '/' | '/guide' | '/lab' | '/matchup' | '/dex/$id' | '/dex/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRoute
  LabRoute: typeof LabRoute
  MatchupRoute: typeof MatchupRoute
  DexIdRoute: typeof DexIdRoute
  DexIndexRoute: typeof DexIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchup': {
      id: '/matchup'
      path: '/matchup'
      fullPath: '/matchup'
      preLoaderRoute: typeof MatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex/': {
      id: '/dex/'
      path: '/dex'
      fullPath: '/dex/'
      preLoaderRoute: typeof DexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dex/$id': {
      id: '/dex/$id'
      path: '/dex/$id'
      fullPath: '/dex/$id'
      preLoaderRoute: typeof DexIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRoute,
  LabRoute: LabRoute,
  MatchupRoute: MatchupRoute,
  DexIdRoute: DexIdRoute,
  DexIndexRoute: DexIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
